/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : DMA,CACHE,TRGMUX,EMIOS,LCU,ETIMER,LLC,SPFU
*   Dependencies         : none
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 2.0.0
*   Build Version        : S32ZE_RTD_2_0_0_D2407_ASR_REL_4_7_REV_0000_20240726
*
*   Copyright 2021-2024 NXP
*   
*
*   NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be 
*   used strictly in accordance with the applicable license terms.  By expressly 
*   accepting such terms or by downloading, installing, activating and/or otherwise 
*   using the software, you are agreeing that you have read, and that you agree to 
*   comply with and are bound by, such license terms.  If you do not agree to be 
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/

/* Prevention from multiple including the same header */
#ifndef TRGMUX_IP_CFG_DEFINES_H_
#define TRGMUX_IP_CFG_DEFINES_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "Std_Types.h"


/*==================================================================================================
*                                 SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define TRGMUX_IP_CFG_DEFINES_VENDOR_ID                    43
#define TRGMUX_IP_CFG_DEFINES_MODULE_ID                    255
#define TRGMUX_IP_CFG_DEFINES_AR_RELEASE_MAJOR_VERSION     4
#define TRGMUX_IP_CFG_DEFINES_AR_RELEASE_MINOR_VERSION     7
#define TRGMUX_IP_CFG_DEFINES_AR_RELEASE_REVISION_VERSION  0
#define TRGMUX_IP_CFG_DEFINES_SW_MAJOR_VERSION             2
#define TRGMUX_IP_CFG_DEFINES_SW_MINOR_VERSION             0
#define TRGMUX_IP_CFG_DEFINES_SW_PATCH_VERSION             0

/*==================================================================================================
                                      FILE VERSION CHECKS
==================================================================================================*/
#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
/* Check if header file and Std_Types header file are of the same Autosar version */
#if ((TRGMUX_IP_CFG_DEFINES_AR_RELEASE_MAJOR_VERSION != STD_AR_RELEASE_MAJOR_VERSION) || \
     (TRGMUX_IP_CFG_DEFINES_AR_RELEASE_MINOR_VERSION != STD_AR_RELEASE_MINOR_VERSION))
    #error "AutoSar Version Numbers of Trgmux_Ip_Cfg_Defines.h and Std_Types.h are different"
#endif
#endif

/*==================================================================================================
*                                       DEFINES AND MACROS
==================================================================================================*/
/*-----------------------------------------------/
/  TRGMUX IP USER MODE SUPPORT                   /
/-----------------------------------------------*/
#define TRGMUX_IP_USER_MODE_SUPPORT_IS_AVAILABLE      STD_OFF

#define TRGMUX_IP_IS_AVAILABLE                   STD_OFF
#define TRGMUX_IP_MULTICORE_IS_AVAILABLE         STD_OFF

/*-----------------------------------------------/
/  TRGMUX IP DEV ERROR DETECT SUPPORT            /
/-----------------------------------------------*/
#define TRGMUX_IP_DEV_ERROR_DETECT               STD_OFF

/*-----------------------------------------------/
/  TRGMUX HARDWARE INSTANCE                      /
/-----------------------------------------------*/
#define TRGMUX_IP_HW_INST_0                      ((uint8)0U)
#define TRGMUX_IP_HW_INST_1                      ((uint8)1U)
#define TRGMUX_IP_HW_INST_2                      ((uint8)2U)
#define TRGMUX_IP_HW_INST_3                      ((uint8)3U)

/*-----------------------------------------------/
/  TRGMUX HARDWARE TRIGGER INPUT                 /
/-----------------------------------------------*/

/*Trgmux 0*/
#define TRGMUX_IP_INPUT_LOGIC0_VSS                          ((uint8)0U)
#define TRGMUX_IP_INPUT_LOGIC0_VDD                          ((uint8)1U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN0                       ((uint8)2U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN1                       ((uint8)3U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN2                       ((uint8)4U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN3                       ((uint8)5U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN4                       ((uint8)6U)
#define TRGMUX_IP_INPUT_TRGMUX_0_XIN5                       ((uint8)7U)
#define TRGMUX_IP_INPUT_EMIOS0_CH0                          ((uint8)8U)
#define TRGMUX_IP_INPUT_EMIOS0_CH1                          ((uint8)9U)
#define TRGMUX_IP_INPUT_EMIOS0_CH2                          ((uint8)10U)
#define TRGMUX_IP_INPUT_EMIOS0_CH3                          ((uint8)11U)
#define TRGMUX_IP_INPUT_EMIOS0_CH4                          ((uint8)12U)
#define TRGMUX_IP_INPUT_EMIOS0_CH5                          ((uint8)13U)
#define TRGMUX_IP_INPUT_EMIOS0_CH6                          ((uint8)14U)
#define TRGMUX_IP_INPUT_EMIOS0_CH7                          ((uint8)15U)
#define TRGMUX_IP_INPUT_EMIOS0_CH16                         ((uint8)16U)
#define TRGMUX_IP_INPUT_EMIOS0_CH17                         ((uint8)17U)
#define TRGMUX_IP_INPUT_EMIOS0_CH18                         ((uint8)18U)
#define TRGMUX_IP_INPUT_EMIOS0_CH19                         ((uint8)19U)
#define TRGMUX_IP_INPUT_EMIOS0_CH20                         ((uint8)20U)
#define TRGMUX_IP_INPUT_EMIOS0_CH21                         ((uint8)21U)
#define TRGMUX_IP_INPUT_EMIOS0_CH22                         ((uint8)22U)
#define TRGMUX_IP_INPUT_EMIOS0_CH23                         ((uint8)23U)
#define TRGMUX_IP_INPUT_EMIOS0_CH24                         ((uint8)24U)
#define TRGMUX_IP_INPUT_EMIOS0_CH25                         ((uint8)25U)
#define TRGMUX_IP_INPUT_EMIOS0_CH26                         ((uint8)26U)
#define TRGMUX_IP_INPUT_EMIOS0_CH27                         ((uint8)27U)
#define TRGMUX_IP_INPUT_EMIOS0_CH28                         ((uint8)28U)
#define TRGMUX_IP_INPUT_EMIOS0_CH29                         ((uint8)29U)
#define TRGMUX_IP_INPUT_EMIOS0_CH30                         ((uint8)30U)
#define TRGMUX_IP_INPUT_EMIOS0_CH31                         ((uint8)31U)
#define TRGMUX_IP_INPUT_LCU0_OUT_8                          ((uint8)32U)
#define TRGMUX_IP_INPUT_LCU0_OUT_9                          ((uint8)33U)
#define TRGMUX_IP_INPUT_LCU0_OUT_10                         ((uint8)34U)
#define TRGMUX_IP_INPUT_LCU0_OUT_11                         ((uint8)35U)

/*Trgmux 1*/
#define TRGMUX_IP_INPUT_LOGIC1_VSS                          ((uint8)0U)
#define TRGMUX_IP_INPUT_LOGIC1_VDD                          ((uint8)1U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN0                       ((uint8)2U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN1                       ((uint8)3U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN2                       ((uint8)4U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN3                       ((uint8)5U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN4                       ((uint8)6U)
#define TRGMUX_IP_INPUT_TRGMUX_1_XIN5                       ((uint8)7U)
#define TRGMUX_IP_INPUT_EMIOS1_CH0                          ((uint8)8U)
#define TRGMUX_IP_INPUT_EMIOS1_CH1                          ((uint8)9U)
#define TRGMUX_IP_INPUT_EMIOS1_CH2                          ((uint8)10U)
#define TRGMUX_IP_INPUT_EMIOS1_CH3                          ((uint8)11U)
#define TRGMUX_IP_INPUT_EMIOS1_CH4                          ((uint8)12U)
#define TRGMUX_IP_INPUT_EMIOS1_CH5                          ((uint8)13U)
#define TRGMUX_IP_INPUT_EMIOS1_CH6                          ((uint8)14U)
#define TRGMUX_IP_INPUT_EMIOS1_CH7                          ((uint8)15U)
#define TRGMUX_IP_INPUT_EMIOS1_CH16                         ((uint8)16U)
#define TRGMUX_IP_INPUT_EMIOS1_CH17                         ((uint8)17U)
#define TRGMUX_IP_INPUT_EMIOS1_CH18                         ((uint8)18U)
#define TRGMUX_IP_INPUT_EMIOS1_CH19                         ((uint8)19U)
#define TRGMUX_IP_INPUT_EMIOS1_CH20                         ((uint8)20U)
#define TRGMUX_IP_INPUT_EMIOS1_CH21                         ((uint8)21U)
#define TRGMUX_IP_INPUT_EMIOS1_CH22                         ((uint8)22U)
#define TRGMUX_IP_INPUT_EMIOS1_CH23                         ((uint8)23U)
#define TRGMUX_IP_INPUT_EMIOS1_CH24                         ((uint8)24U)
#define TRGMUX_IP_INPUT_EMIOS1_CH25                         ((uint8)25U)
#define TRGMUX_IP_INPUT_EMIOS1_CH26                         ((uint8)26U)
#define TRGMUX_IP_INPUT_EMIOS1_CH27                         ((uint8)27U)
#define TRGMUX_IP_INPUT_EMIOS1_CH28                         ((uint8)28U)
#define TRGMUX_IP_INPUT_EMIOS1_CH29                         ((uint8)29U)
#define TRGMUX_IP_INPUT_EMIOS1_CH30                         ((uint8)30U)
#define TRGMUX_IP_INPUT_EMIOS1_CH31                         ((uint8)31U)
#define TRGMUX_IP_INPUT_LCU1_OUT_8                          ((uint8)32U)
#define TRGMUX_IP_INPUT_LCU1_OUT_9                          ((uint8)33U)
#define TRGMUX_IP_INPUT_LCU1_OUT_10                         ((uint8)34U)
#define TRGMUX_IP_INPUT_LCU1_OUT_11                         ((uint8)35U)

/*Trgmux 2*/
#define TRGMUX_IP_INPUT_GTM_000                             ((uint8)0U)
#define TRGMUX_IP_INPUT_GTM_001                             ((uint8)1U)
#define TRGMUX_IP_INPUT_GTM_002                             ((uint8)2U)
#define TRGMUX_IP_INPUT_GTM_003                             ((uint8)3U)
#define TRGMUX_IP_INPUT_GTM_004                             ((uint8)4U)
#define TRGMUX_IP_INPUT_GTM_005                             ((uint8)5U)
#define TRGMUX_IP_INPUT_GTM_006                             ((uint8)6U)
#define TRGMUX_IP_INPUT_GTM_007                             ((uint8)7U)
#define TRGMUX_IP_INPUT_GTM_008                             ((uint8)8U)
#define TRGMUX_IP_INPUT_GTM_009                             ((uint8)9U)
#define TRGMUX_IP_INPUT_GTM_010                             ((uint8)10U)
#define TRGMUX_IP_INPUT_GTM_011                             ((uint8)11U)
#define TRGMUX_IP_INPUT_GTM_012                             ((uint8)12U)
#define TRGMUX_IP_INPUT_GTM_013                             ((uint8)13U)
#define TRGMUX_IP_INPUT_GTM_014                             ((uint8)14U)
#define TRGMUX_IP_INPUT_GTM_015                             ((uint8)15U)
#define TRGMUX_IP_INPUT_GTM_016                             ((uint8)16U)
#define TRGMUX_IP_INPUT_GTM_017                             ((uint8)17U)
#define TRGMUX_IP_INPUT_GTM_018                             ((uint8)18U)
#define TRGMUX_IP_INPUT_GTM_019                             ((uint8)19U)
#define TRGMUX_IP_INPUT_GTM_020                             ((uint8)20U)
#define TRGMUX_IP_INPUT_GTM_021                             ((uint8)21U)
#define TRGMUX_IP_INPUT_GTM_022                             ((uint8)22U)
#define TRGMUX_IP_INPUT_GTM_023                             ((uint8)23U)
#define TRGMUX_IP_INPUT_GTM_024                             ((uint8)24U)
#define TRGMUX_IP_INPUT_GTM_025                             ((uint8)25U)
#define TRGMUX_IP_INPUT_GTM_026                             ((uint8)26U)
#define TRGMUX_IP_INPUT_GTM_027                             ((uint8)27U)
#define TRGMUX_IP_INPUT_GTM_028                             ((uint8)28U)
#define TRGMUX_IP_INPUT_GTM_029                             ((uint8)29U)
#define TRGMUX_IP_INPUT_GTM_030                             ((uint8)30U)
#define TRGMUX_IP_INPUT_GTM_031                             ((uint8)31U)
#define TRGMUX_IP_INPUT_GTM_032                             ((uint8)32U)
#define TRGMUX_IP_INPUT_GTM_033                             ((uint8)33U)
#define TRGMUX_IP_INPUT_GTM_034                             ((uint8)34U)
#define TRGMUX_IP_INPUT_GTM_035                             ((uint8)35U)
#define TRGMUX_IP_INPUT_GTM_036                             ((uint8)36U)
#define TRGMUX_IP_INPUT_GTM_037                             ((uint8)37U)
#define TRGMUX_IP_INPUT_GTM_038                             ((uint8)38U)
#define TRGMUX_IP_INPUT_GTM_039                             ((uint8)39U)
#define TRGMUX_IP_INPUT_GTM_040                             ((uint8)40U)
#define TRGMUX_IP_INPUT_GTM_041                             ((uint8)41U)
#define TRGMUX_IP_INPUT_GTM_042                             ((uint8)42U)
#define TRGMUX_IP_INPUT_GTM_043                             ((uint8)43U)
#define TRGMUX_IP_INPUT_GTM_044                             ((uint8)44U)
#define TRGMUX_IP_INPUT_GTM_045                             ((uint8)45U)
#define TRGMUX_IP_INPUT_GTM_046                             ((uint8)46U)
#define TRGMUX_IP_INPUT_GTM_047                             ((uint8)47U)
#define TRGMUX_IP_INPUT_GTM_048                             ((uint8)48U)
#define TRGMUX_IP_INPUT_GTM_049                             ((uint8)49U)
#define TRGMUX_IP_INPUT_GTM_050                             ((uint8)50U)
#define TRGMUX_IP_INPUT_GTM_051                             ((uint8)51U)
#define TRGMUX_IP_INPUT_GTM_052                             ((uint8)52U)
#define TRGMUX_IP_INPUT_GTM_053                             ((uint8)53U)
#define TRGMUX_IP_INPUT_GTM_054                             ((uint8)54U)
#define TRGMUX_IP_INPUT_GTM_055                             ((uint8)55U)
#define TRGMUX_IP_INPUT_GTM_056                             ((uint8)56U)
#define TRGMUX_IP_INPUT_GTM_057                             ((uint8)57U)
#define TRGMUX_IP_INPUT_GTM_058                             ((uint8)58U)
#define TRGMUX_IP_INPUT_GTM_059                             ((uint8)59U)
#define TRGMUX_IP_INPUT_GTM_060                             ((uint8)60U)
#define TRGMUX_IP_INPUT_GTM_061                             ((uint8)61U)
#define TRGMUX_IP_INPUT_GTM_062                             ((uint8)62U)
#define TRGMUX_IP_INPUT_GTM_063                             ((uint8)63U)
#define TRGMUX_IP_INPUT_GTM_064                             ((uint8)64U)
#define TRGMUX_IP_INPUT_GTM_065                             ((uint8)65U)
#define TRGMUX_IP_INPUT_GTM_066                             ((uint8)66U)
#define TRGMUX_IP_INPUT_GTM_067                             ((uint8)67U)
#define TRGMUX_IP_INPUT_GTM_068                             ((uint8)68U)
#define TRGMUX_IP_INPUT_GTM_069                             ((uint8)69U)
#define TRGMUX_IP_INPUT_GTM_070                             ((uint8)70U)
#define TRGMUX_IP_INPUT_GTM_071                             ((uint8)71U)
#define TRGMUX_IP_INPUT_GTM_072                             ((uint8)72U)
#define TRGMUX_IP_INPUT_GTM_073                             ((uint8)73U)
#define TRGMUX_IP_INPUT_GTM_074                             ((uint8)74U)
#define TRGMUX_IP_INPUT_GTM_075                             ((uint8)75U)
#define TRGMUX_IP_INPUT_GTM_076                             ((uint8)76U)
#define TRGMUX_IP_INPUT_GTM_077                             ((uint8)77U)
#define TRGMUX_IP_INPUT_GTM_078                             ((uint8)78U)
#define TRGMUX_IP_INPUT_GTM_079                             ((uint8)79U)
#define TRGMUX_IP_INPUT_GTM_080                             ((uint8)80U)
#define TRGMUX_IP_INPUT_GTM_081                             ((uint8)81U)
#define TRGMUX_IP_INPUT_GTM_082                             ((uint8)82U)
#define TRGMUX_IP_INPUT_GTM_083                             ((uint8)83U)
#define TRGMUX_IP_INPUT_GTM_084                             ((uint8)84U)
#define TRGMUX_IP_INPUT_GTM_085                             ((uint8)85U)
#define TRGMUX_IP_INPUT_GTM_086                             ((uint8)86U)
#define TRGMUX_IP_INPUT_GTM_087                             ((uint8)87U)
#define TRGMUX_IP_INPUT_GTM_088                             ((uint8)88U)
#define TRGMUX_IP_INPUT_GTM_089                             ((uint8)89U)
#define TRGMUX_IP_INPUT_GTM_090                             ((uint8)90U)
#define TRGMUX_IP_INPUT_GTM_091                             ((uint8)91U)
#define TRGMUX_IP_INPUT_GTM_092                             ((uint8)92U)
#define TRGMUX_IP_INPUT_GTM_093                             ((uint8)93U)
#define TRGMUX_IP_INPUT_GTM_094                             ((uint8)94U)
#define TRGMUX_IP_INPUT_GTM_095                             ((uint8)95U)
#define TRGMUX_IP_INPUT_GTM_096                             ((uint8)96U)
#define TRGMUX_IP_INPUT_GTM_097                             ((uint8)97U)
#define TRGMUX_IP_INPUT_GTM_098                             ((uint8)98U)
#define TRGMUX_IP_INPUT_GTM_099                             ((uint8)99U)
#define TRGMUX_IP_INPUT_GTM_100                             ((uint8)100U)
#define TRGMUX_IP_INPUT_GTM_101                             ((uint8)101U)
#define TRGMUX_IP_INPUT_GTM_102                             ((uint8)102U)
#define TRGMUX_IP_INPUT_GTM_103                             ((uint8)103U)
#define TRGMUX_IP_INPUT_GTM_104                             ((uint8)104U)
#define TRGMUX_IP_INPUT_GTM_105                             ((uint8)105U)
#define TRGMUX_IP_INPUT_GTM_106                             ((uint8)106U)
#define TRGMUX_IP_INPUT_GTM_107                             ((uint8)107U)
#define TRGMUX_IP_INPUT_GTM_180                             ((uint8)108U)
#define TRGMUX_IP_INPUT_GTM_190                             ((uint8)109U)
#define TRGMUX_IP_INPUT_GTM_110                             ((uint8)110U)
#define TRGMUX_IP_INPUT_GTM_111                             ((uint8)111U)
#define TRGMUX_IP_INPUT_GTM_112                             ((uint8)112U)
#define TRGMUX_IP_INPUT_GTM_113                             ((uint8)113U)
#define TRGMUX_IP_INPUT_GTM_114                             ((uint8)114U)
#define TRGMUX_IP_INPUT_GTM_115                             ((uint8)115U)
#define TRGMUX_IP_INPUT_GTM_116                             ((uint8)116U)
#define TRGMUX_IP_INPUT_GTM_117                             ((uint8)117U)
#define TRGMUX_IP_INPUT_GTM_118                             ((uint8)118U)
#define TRGMUX_IP_INPUT_GTM_119                             ((uint8)119U)
#define TRGMUX_IP_INPUT_GTM_120                             ((uint8)120U)
#define TRGMUX_IP_INPUT_GTM_121                             ((uint8)121U)
#define TRGMUX_IP_INPUT_GTM_122                             ((uint8)122U)
#define TRGMUX_IP_INPUT_GTM_123                             ((uint8)123U)
#define TRGMUX_IP_INPUT_GTM_124                             ((uint8)124U)
#define TRGMUX_IP_INPUT_GTM_125                             ((uint8)125U)
#define TRGMUX_IP_INPUT_GTM_126                             ((uint8)126U)
#define TRGMUX_IP_INPUT_GTM_127                             ((uint8)127U)
#define TRGMUX_IP_INPUT_GTM_128                             ((uint8)128U)
#define TRGMUX_IP_INPUT_GTM_129                             ((uint8)129U)
#define TRGMUX_IP_INPUT_GTM_130                             ((uint8)130U)
#define TRGMUX_IP_INPUT_GTM_131                             ((uint8)131U)
#define TRGMUX_IP_INPUT_GTM_132                             ((uint8)132U)
#define TRGMUX_IP_INPUT_GTM_133                             ((uint8)133U)
#define TRGMUX_IP_INPUT_GTM_134                             ((uint8)134U)
#define TRGMUX_IP_INPUT_GTM_135                             ((uint8)135U)
#define TRGMUX_IP_INPUT_GTM_136                             ((uint8)136U)
#define TRGMUX_IP_INPUT_GTM_137                             ((uint8)137U)
#define TRGMUX_IP_INPUT_GTM_138                             ((uint8)138U)
#define TRGMUX_IP_INPUT_GTM_139                             ((uint8)139U)
#define TRGMUX_IP_INPUT_GTM_140                             ((uint8)140U)
#define TRGMUX_IP_INPUT_GTM_141                             ((uint8)141U)
#define TRGMUX_IP_INPUT_GTM_142                             ((uint8)142U)
#define TRGMUX_IP_INPUT_GTM_143                             ((uint8)143U)
#define TRGMUX_IP_INPUT_GTM_144                             ((uint8)144U)
#define TRGMUX_IP_INPUT_GTM_145                             ((uint8)145U)
#define TRGMUX_IP_INPUT_GTM_146                             ((uint8)146U)
#define TRGMUX_IP_INPUT_GTM_147                             ((uint8)147U)
#define TRGMUX_IP_INPUT_GTM_148                             ((uint8)148U)
#define TRGMUX_IP_INPUT_GTM_149                             ((uint8)149U)
#define TRGMUX_IP_INPUT_GTM_150                             ((uint8)150U)
#define TRGMUX_IP_INPUT_GTM_151                             ((uint8)151U)
#define TRGMUX_IP_INPUT_GTM_152                             ((uint8)152U)
#define TRGMUX_IP_INPUT_GTM_153                             ((uint8)153U)
#define TRGMUX_IP_INPUT_GTM_154                             ((uint8)154U)
#define TRGMUX_IP_INPUT_GTM_155                             ((uint8)155U)
#define TRGMUX_IP_INPUT_GTM_156                             ((uint8)156U)
#define TRGMUX_IP_INPUT_GTM_157                             ((uint8)157U)
#define TRGMUX_IP_INPUT_GTM_158                             ((uint8)158U)
#define TRGMUX_IP_INPUT_GTM_159                             ((uint8)159U)
#define TRGMUX_IP_INPUT_GTM_160                             ((uint8)160U)
#define TRGMUX_IP_INPUT_GTM_161                             ((uint8)161U)
#define TRGMUX_IP_INPUT_GTM_162                             ((uint8)162U)
#define TRGMUX_IP_INPUT_GTM_163                             ((uint8)163U)
#define TRGMUX_IP_INPUT_GTM_164                             ((uint8)164U)
#define TRGMUX_IP_INPUT_GTM_165                             ((uint8)165U)
#define TRGMUX_IP_INPUT_GTM_166                             ((uint8)166U)
#define TRGMUX_IP_INPUT_GTM_167                             ((uint8)167U)
#define TRGMUX_IP_INPUT_GTM_168                             ((uint8)168U)
#define TRGMUX_IP_INPUT_SINC_CC0                            ((uint8)169U)
#define TRGMUX_IP_INPUT_SINC_CC1                            ((uint8)170U)
#define TRGMUX_IP_INPUT_SINC_CC2                            ((uint8)171U)
#define TRGMUX_IP_INPUT_SINC_CC3                            ((uint8)172U)


/*Trgmux 3*/

#define TRGMUX_IP_INPUT_TOM0_CH0                            ((uint8)0U)
#define TRGMUX_IP_INPUT_TOM0_CH1                            ((uint8)1U)
#define TRGMUX_IP_INPUT_TOM0_CH2                            ((uint8)2U)
#define TRGMUX_IP_INPUT_TOM0_CH3                            ((uint8)3U)
#define TRGMUX_IP_INPUT_TOM0_CH4                            ((uint8)4U)
#define TRGMUX_IP_INPUT_TOM0_CH5                            ((uint8)5U)
#define TRGMUX_IP_INPUT_TOM0_CH6                            ((uint8)6U)
#define TRGMUX_IP_INPUT_TOM0_CH7                            ((uint8)7U)
#define TRGMUX_IP_INPUT_TOM0_CH8                            ((uint8)8U)
#define TRGMUX_IP_INPUT_TOM0_CH9                            ((uint8)9U)
#define TRGMUX_IP_INPUT_TOM0_CH10                           ((uint8)10U)
#define TRGMUX_IP_INPUT_TOM0_CH11                           ((uint8)11U)
#define TRGMUX_IP_INPUT_TOM0_CH12                           ((uint8)12U)
#define TRGMUX_IP_INPUT_TOM0_CH13                           ((uint8)13U)
#define TRGMUX_IP_INPUT_TOM0_CH14                           ((uint8)14U)
#define TRGMUX_IP_INPUT_TOM0_CH15                           ((uint8)15U)
#define TRGMUX_IP_INPUT_TOM1_CH0                            ((uint8)16U)
#define TRGMUX_IP_INPUT_TOM1_CH1                            ((uint8)17U)
#define TRGMUX_IP_INPUT_TOM1_CH2                            ((uint8)18U)
#define TRGMUX_IP_INPUT_TOM1_CH3                            ((uint8)19U)
#define TRGMUX_IP_INPUT_TOM1_CH4                            ((uint8)20U)
#define TRGMUX_IP_INPUT_TOM1_CH5                            ((uint8)21U)
#define TRGMUX_IP_INPUT_TOM1_CH6                            ((uint8)22U)
#define TRGMUX_IP_INPUT_TOM1_CH7                            ((uint8)23U)
#define TRGMUX_IP_INPUT_TOM1_CH8                            ((uint8)24U)
#define TRGMUX_IP_INPUT_TOM1_CH9                            ((uint8)25U)
#define TRGMUX_IP_INPUT_TOM1_CH10                           ((uint8)26U)
#define TRGMUX_IP_INPUT_TOM1_CH11                           ((uint8)27U)
#define TRGMUX_IP_INPUT_TOM1_CH12                           ((uint8)28U)
#define TRGMUX_IP_INPUT_TOM1_CH13                           ((uint8)29U)
#define TRGMUX_IP_INPUT_TOM1_CH14                           ((uint8)30U)
#define TRGMUX_IP_INPUT_TOM1_CH15                           ((uint8)31U)
#define TRGMUX_IP_INPUT_ATOM0_CH0_0                         ((uint8)32U)
#define TRGMUX_IP_INPUT_ATOM0_CH1_0                         ((uint8)33U)
#define TRGMUX_IP_INPUT_ATOM0_CH2_0                         ((uint8)34U)
#define TRGMUX_IP_INPUT_ATOM0_CH3_0                         ((uint8)35U)
#define TRGMUX_IP_INPUT_ATOM0_CH4_0                         ((uint8)36U)
#define TRGMUX_IP_INPUT_ATOM0_CH5_0                         ((uint8)37U)
#define TRGMUX_IP_INPUT_ATOM0_CH6_0                         ((uint8)38U)
#define TRGMUX_IP_INPUT_ATOM0_CH7_0                         ((uint8)39U)
#define TRGMUX_IP_INPUT_ATOM0_CH0_1                         ((uint8)40U)
#define TRGMUX_IP_INPUT_ATOM0_CH1_1                         ((uint8)41U)
#define TRGMUX_IP_INPUT_ATOM0_CH2_1                         ((uint8)42U)
#define TRGMUX_IP_INPUT_ATOM0_CH3_1                         ((uint8)43U)
#define TRGMUX_IP_INPUT_ATOM0_CH4_1                         ((uint8)44U)
#define TRGMUX_IP_INPUT_ATOM0_CH5_1                         ((uint8)45U)
#define TRGMUX_IP_INPUT_ATOM0_CH6_1                         ((uint8)46U)
#define TRGMUX_IP_INPUT_ATOM0_CH7_1                         ((uint8)47U)
#define TRGMUX_IP_INPUT_ATOM1_CH0_0                         ((uint8)48U)
#define TRGMUX_IP_INPUT_ATOM1_CH1_0                         ((uint8)49U)
#define TRGMUX_IP_INPUT_ATOM1_CH2_0                         ((uint8)50U)
#define TRGMUX_IP_INPUT_ATOM1_CH3_0                         ((uint8)51U)
#define TRGMUX_IP_INPUT_ATOM1_CH4_0                         ((uint8)52U)
#define TRGMUX_IP_INPUT_ATOM1_CH5_0                         ((uint8)53U)
#define TRGMUX_IP_INPUT_ATOM1_CH6_0                         ((uint8)54U)
#define TRGMUX_IP_INPUT_ATOM1_CH7_0                         ((uint8)55U)
#define TRGMUX_IP_INPUT_ATOM1_CH0_1                         ((uint8)56U)
#define TRGMUX_IP_INPUT_ATOM1_CH1_1                         ((uint8)57U)
#define TRGMUX_IP_INPUT_ATOM1_CH2_1                         ((uint8)58U)
#define TRGMUX_IP_INPUT_ATOM1_CH3_1                         ((uint8)59U)
#define TRGMUX_IP_INPUT_ATOM1_CH4_1                         ((uint8)60U)
#define TRGMUX_IP_INPUT_ATOM1_CH5_1                         ((uint8)61U)
#define TRGMUX_IP_INPUT_ATOM1_CH6_1                         ((uint8)62U)
#define TRGMUX_IP_INPUT_ATOM1_CH7_1                         ((uint8)63U)
#define TRGMUX_IP_INPUT_ATOM2_CH0_0                         ((uint8)64U)
#define TRGMUX_IP_INPUT_ATOM2_CH1_0                         ((uint8)65U)
#define TRGMUX_IP_INPUT_ATOM2_CH2_0                         ((uint8)66U)
#define TRGMUX_IP_INPUT_ATOM2_CH3_0                         ((uint8)67U)
#define TRGMUX_IP_INPUT_ATOM2_CH4_0                         ((uint8)68U)
#define TRGMUX_IP_INPUT_ATOM2_CH5_0                         ((uint8)69U)
#define TRGMUX_IP_INPUT_ATOM2_CH6_0                         ((uint8)70U)
#define TRGMUX_IP_INPUT_ATOM2_CH7_0                         ((uint8)71U)
#define TRGMUX_IP_INPUT_ATOM2_CH0_1                         ((uint8)72U)
#define TRGMUX_IP_INPUT_ATOM2_CH1_1                         ((uint8)73U)
#define TRGMUX_IP_INPUT_ATOM2_CH2_1                         ((uint8)74U)
#define TRGMUX_IP_INPUT_ATOM2_CH3_1                         ((uint8)75U)
#define TRGMUX_IP_INPUT_ATOM2_CH4_1                         ((uint8)76U)
#define TRGMUX_IP_INPUT_ATOM2_CH5_1                         ((uint8)77U)
#define TRGMUX_IP_INPUT_ATOM2_CH6_1                         ((uint8)78U)
#define TRGMUX_IP_INPUT_ATOM2_CH7_1                         ((uint8)79U)
#define TRGMUX_IP_INPUT_ATOM3_CH0_0                         ((uint8)80U)
#define TRGMUX_IP_INPUT_ATOM3_CH1_0                         ((uint8)81U)
#define TRGMUX_IP_INPUT_ATOM3_CH2_0                         ((uint8)82U)
#define TRGMUX_IP_INPUT_ATOM3_CH3_0                         ((uint8)83U)
#define TRGMUX_IP_INPUT_ATOM3_CH4_0                         ((uint8)84U)
#define TRGMUX_IP_INPUT_ATOM3_CH5_0                         ((uint8)85U)
#define TRGMUX_IP_INPUT_ATOM3_CH6_0                         ((uint8)86U)
#define TRGMUX_IP_INPUT_ATOM3_CH7_0                         ((uint8)87U)
#define TRGMUX_IP_INPUT_ATOM3_CH0_1                         ((uint8)88U)
#define TRGMUX_IP_INPUT_ATOM3_CH1_1                         ((uint8)89U)
#define TRGMUX_IP_INPUT_ATOM3_CH2_1                         ((uint8)90U)
#define TRGMUX_IP_INPUT_ATOM3_CH3_1                         ((uint8)91U)
#define TRGMUX_IP_INPUT_ATOM3_CH4_1                         ((uint8)92U)
#define TRGMUX_IP_INPUT_ATOM3_CH5_1                         ((uint8)93U)
#define TRGMUX_IP_INPUT_ATOM3_CH6_1                         ((uint8)94U)
#define TRGMUX_IP_INPUT_ATOM3_CH7_1                         ((uint8)95U)
#define TRGMUX_IP_INPUT_TIO1_CH0                            ((uint8)96U)
#define TRGMUX_IP_INPUT_TIO1_CH1                            ((uint8)97U)
#define TRGMUX_IP_INPUT_TIO1_CH2                            ((uint8)98U)
#define TRGMUX_IP_INPUT_TIO1_CH3                            ((uint8)99U)
#define TRGMUX_IP_INPUT_TIO1_CH4                            ((uint8)100U)
#define TRGMUX_IP_INPUT_TIO1_CH5                            ((uint8)101U)
#define TRGMUX_IP_INPUT_TIO1_CH6                            ((uint8)102U)
#define TRGMUX_IP_INPUT_TIO1_CH7                            ((uint8)103U)
#define TRGMUX_IP_INPUT_TIO2_CH0                            ((uint8)104U)
#define TRGMUX_IP_INPUT_TIO2_CH1                            ((uint8)105U)
#define TRGMUX_IP_INPUT_TIO2_CH2                            ((uint8)106U)
#define TRGMUX_IP_INPUT_TIO2_CH3                            ((uint8)107U)
#define TRGMUX_IP_INPUT_TIO2_CH4                            ((uint8)108U)
#define TRGMUX_IP_INPUT_TIO2_CH5                            ((uint8)109U)
#define TRGMUX_IP_INPUT_TIO2_CH6                            ((uint8)110U)
#define TRGMUX_IP_INPUT_TIO2_CH7                            ((uint8)111U)
#define TRGMUX_IP_INPUT_TIO3_CH0                            ((uint8)112U)
#define TRGMUX_IP_INPUT_TIO3_CH1                            ((uint8)113U)
#define TRGMUX_IP_INPUT_TIO3_CH2                            ((uint8)114U)
#define TRGMUX_IP_INPUT_TIO3_CH3                            ((uint8)115U)
#define TRGMUX_IP_INPUT_TIO3_CH4                            ((uint8)116U)
#define TRGMUX_IP_INPUT_TIO3_CH5                            ((uint8)117U)
#define TRGMUX_IP_INPUT_TIO3_CH6                            ((uint8)118U)
#define TRGMUX_IP_INPUT_TIO3_CH7                            ((uint8)119U)
/*-----------------------------------------------/
/  TRGMUX HARDWARE TRIGGER OUTPUT                /
/-----------------------------------------------*/

/*Trgmux 0*/
#define TRGMUX_IP_LCU0_IN_0                                 ((uint8)0U)
#define TRGMUX_IP_LCU0_IN_1                                 ((uint8)1U)
#define TRGMUX_IP_LCU0_IN_2                                 ((uint8)2U)
#define TRGMUX_IP_LCU0_IN_3                                 ((uint8)3U)
#define TRGMUX_IP_LCU0_IN_4                                 ((uint8)4U)
#define TRGMUX_IP_LCU0_IN_5                                 ((uint8)5U)
#define TRGMUX_IP_LCU0_IN_6                                 ((uint8)6U)
#define TRGMUX_IP_LCU0_IN_7                                 ((uint8)7U)
#define TRGMUX_IP_LCU0_IN_8                                 ((uint8)8U)
#define TRGMUX_IP_LCU0_IN_9                                 ((uint8)9U)
#define TRGMUX_IP_LCU0_IN_10                                ((uint8)10U)
#define TRGMUX_IP_LCU0_IN_11                                ((uint8)11U)
#define TRGMUX_IP_LCU0_FORCE_0                              ((uint8)12U)
#define TRGMUX_IP_LCU0_FORCE_1                              ((uint8)13U)
#define TRGMUX_IP_LCU0_FORCE_2                              ((uint8)14U)
#define TRGMUX_IP_LCU0_FORCE_3                              ((uint8)15U)
#define TRGMUX_IP_LCU0_SYNC_0                               ((uint8)16U)
#define TRGMUX_IP_LCU0_SYNC_1                               ((uint8)17U)

/*Trgmux 1*/
#define TRGMUX_IP_LCU1_IN_0                                 ((uint8)0U)
#define TRGMUX_IP_LCU1_IN_1                                 ((uint8)1U)
#define TRGMUX_IP_LCU1_IN_2                                 ((uint8)2U)
#define TRGMUX_IP_LCU1_IN_3                                 ((uint8)3U)
#define TRGMUX_IP_LCU1_IN_4                                 ((uint8)4U)
#define TRGMUX_IP_LCU1_IN_5                                 ((uint8)5U)
#define TRGMUX_IP_LCU1_IN_6                                 ((uint8)6U)
#define TRGMUX_IP_LCU1_IN_7                                 ((uint8)7U)
#define TRGMUX_IP_LCU1_IN_8                                 ((uint8)8U)
#define TRGMUX_IP_LCU1_IN_9                                 ((uint8)9U)
#define TRGMUX_IP_LCU1_IN_10                                ((uint8)10U)
#define TRGMUX_IP_LCU1_IN_11                                ((uint8)11U)
#define TRGMUX_IP_LCU1_FORCE_0                              ((uint8)12U)
#define TRGMUX_IP_LCU1_FORCE_1                              ((uint8)13U)
#define TRGMUX_IP_LCU1_FORCE_2                              ((uint8)14U)
#define TRGMUX_IP_LCU1_FORCE_3                              ((uint8)15U)
#define TRGMUX_IP_LCU1_SYNC_0                               ((uint8)16U)
#define TRGMUX_IP_LCU1_SYNC_1                               ((uint8)17U)

/*Trgmux 2*/
#define TRGMUX_IP_TIM0_CH0                                  ((uint8)0U)
#define TRGMUX_IP_TIM0_CH1                                  ((uint8)1U)
#define TRGMUX_IP_TIM0_CH2                                  ((uint8)4U)
#define TRGMUX_IP_TIM0_CH3                                  ((uint8)5U)
#define TRGMUX_IP_TIM0_CH4                                  ((uint8)8U)
#define TRGMUX_IP_TIM0_CH5                                  ((uint8)9U)
#define TRGMUX_IP_TIM0_CH6                                  ((uint8)12U)
#define TRGMUX_IP_TIM0_CH7                                  ((uint8)13U)
#define TRGMUX_IP_TIM1_CH0                                  ((uint8)16U)
#define TRGMUX_IP_TIM1_CH1                                  ((uint8)17U)
#define TRGMUX_IP_TIM1_CH2                                  ((uint8)20U)
#define TRGMUX_IP_TIM1_CH3                                  ((uint8)21U)
#define TRGMUX_IP_TIM1_CH4                                  ((uint8)24U)
#define TRGMUX_IP_TIM1_CH5                                  ((uint8)25U)
#define TRGMUX_IP_TIM1_CH6                                  ((uint8)28U)
#define TRGMUX_IP_TIM1_CH7                                  ((uint8)29U)
#define TRGMUX_IP_TIM2_CH0                                  ((uint8)32U)
#define TRGMUX_IP_TIM2_CH1                                  ((uint8)33U)
#define TRGMUX_IP_TIM2_CH2                                  ((uint8)36U)
#define TRGMUX_IP_TIM2_CH3                                  ((uint8)37U)
#define TRGMUX_IP_TIM2_CH4                                  ((uint8)40U)
#define TRGMUX_IP_TIM2_CH5                                  ((uint8)41U)
#define TRGMUX_IP_TIM2_CH6                                  ((uint8)44U)
#define TRGMUX_IP_TIM2_CH7                                  ((uint8)45U)
#define TRGMUX_IP_TIO1_CH0                                  ((uint8)48U)
#define TRGMUX_IP_TIO1_CH1                                  ((uint8)49U)
#define TRGMUX_IP_TIO1_CH2                                  ((uint8)52U)
#define TRGMUX_IP_TIO1_CH3                                  ((uint8)53U)
#define TRGMUX_IP_TIO1_CH4                                  ((uint8)56U)
#define TRGMUX_IP_TIO1_CH5                                  ((uint8)57U)
#define TRGMUX_IP_TIO1_CH6                                  ((uint8)60U)
#define TRGMUX_IP_TIO1_CH7                                  ((uint8)61U)
#define TRGMUX_IP_TIO2_CH0                                  ((uint8)64U)
#define TRGMUX_IP_TIO2_CH1                                  ((uint8)65U)
#define TRGMUX_IP_TIO2_CH2                                  ((uint8)68U)
#define TRGMUX_IP_TIO2_CH3                                  ((uint8)69U)
#define TRGMUX_IP_TIO2_CH4                                  ((uint8)72U)
#define TRGMUX_IP_TIO2_CH5                                  ((uint8)73U)
#define TRGMUX_IP_TIO2_CH6                                  ((uint8)76U)
#define TRGMUX_IP_TIO2_CH7                                  ((uint8)77U)
#define TRGMUX_IP_TIO3_CH0                                  ((uint8)80U)
#define TRGMUX_IP_TIO3_CH1                                  ((uint8)81U)
#define TRGMUX_IP_TIO3_CH2                                  ((uint8)84U)
#define TRGMUX_IP_TIO3_CH3                                  ((uint8)85U)
#define TRGMUX_IP_TIO3_CH4                                  ((uint8)88U)
#define TRGMUX_IP_TIO3_CH5                                  ((uint8)89U)
#define TRGMUX_IP_TIO3_CH6                                  ((uint8)92U)
#define TRGMUX_IP_TIO3_CH7                                  ((uint8)93U)

/*Trgmux 3*/
#define TRGMUX_IP_GTM_000                                   ((uint8)0U)
#define TRGMUX_IP_GTM_001                                   ((uint8)1U)
#define TRGMUX_IP_GTM_002                                   ((uint8)2U)
#define TRGMUX_IP_GTM_003                                   ((uint8)3U)
#define TRGMUX_IP_GTM_004                                   ((uint8)4U)
#define TRGMUX_IP_GTM_005                                   ((uint8)5U)
#define TRGMUX_IP_GTM_006                                   ((uint8)6U)
#define TRGMUX_IP_GTM_007                                   ((uint8)7U)
#define TRGMUX_IP_GTM_008                                   ((uint8)8U)
#define TRGMUX_IP_GTM_009                                   ((uint8)9U)
#define TRGMUX_IP_GTM_010                                   ((uint8)10U)
#define TRGMUX_IP_GTM_011                                   ((uint8)11U)
#define TRGMUX_IP_GTM_012                                   ((uint8)12U)
#define TRGMUX_IP_GTM_013                                   ((uint8)13U)
#define TRGMUX_IP_GTM_014                                   ((uint8)14U)
#define TRGMUX_IP_GTM_015                                   ((uint8)15U)
#define TRGMUX_IP_GTM_016                                   ((uint8)16U)
#define TRGMUX_IP_GTM_017                                   ((uint8)17U)
#define TRGMUX_IP_GTM_018                                   ((uint8)18U) 
#define TRGMUX_IP_GTM_019                                   ((uint8)19U)
#define TRGMUX_IP_GTM_020                                   ((uint8)20U)
#define TRGMUX_IP_GTM_021                                   ((uint8)21U)
#define TRGMUX_IP_GTM_022                                   ((uint8)22U)
#define TRGMUX_IP_GTM_023                                   ((uint8)23U)
#define TRGMUX_IP_GTM_024                                   ((uint8)24U)
#define TRGMUX_IP_GTM_025                                   ((uint8)25U)
#define TRGMUX_IP_GTM_026                                   ((uint8)26U)
#define TRGMUX_IP_GTM_027                                   ((uint8)27U)
#define TRGMUX_IP_GTM_028                                   ((uint8)28U)
#define TRGMUX_IP_GTM_029                                   ((uint8)29U)
#define TRGMUX_IP_GTM_030                                   ((uint8)30U)
#define TRGMUX_IP_GTM_031                                   ((uint8)31U)
#define TRGMUX_IP_GTM_032                                   ((uint8)32U)
#define TRGMUX_IP_GTM_033                                   ((uint8)33U)
#define TRGMUX_IP_GTM_034                                   ((uint8)34U)
#define TRGMUX_IP_GTM_035                                   ((uint8)35U)
#define TRGMUX_IP_GTM_036                                   ((uint8)36U)
#define TRGMUX_IP_GTM_037                                   ((uint8)37U)
#define TRGMUX_IP_GTM_038                                   ((uint8)38U)
#define TRGMUX_IP_GTM_039                                   ((uint8)39U)
#define TRGMUX_IP_GTM_040                                   ((uint8)40U)
#define TRGMUX_IP_GTM_041                                   ((uint8)41U)
#define TRGMUX_IP_GTM_042                                   ((uint8)42U)
#define TRGMUX_IP_GTM_043                                   ((uint8)43U)
#define TRGMUX_IP_GTM_044                                   ((uint8)44U)
#define TRGMUX_IP_GTM_045                                   ((uint8)45U)
#define TRGMUX_IP_GTM_046                                   ((uint8)46U)
#define TRGMUX_IP_GTM_047                                   ((uint8)47U)
#define TRGMUX_IP_GTM_048                                   ((uint8)48U)
#define TRGMUX_IP_GTM_049                                   ((uint8)49U)
#define TRGMUX_IP_GTM_050                                   ((uint8)50U)
#define TRGMUX_IP_GTM_051                                   ((uint8)51U)
#define TRGMUX_IP_GTM_052                                   ((uint8)52U)
#define TRGMUX_IP_GTM_053                                   ((uint8)53U)
#define TRGMUX_IP_GTM_054                                   ((uint8)54U)
#define TRGMUX_IP_GTM_055                                   ((uint8)55U)
#define TRGMUX_IP_GTM_056                                   ((uint8)56U)
#define TRGMUX_IP_GTM_057                                   ((uint8)57U)
#define TRGMUX_IP_GTM_058                                   ((uint8)58U)
#define TRGMUX_IP_GTM_059                                   ((uint8)59U)
#define TRGMUX_IP_GTM_060                                   ((uint8)60U)
#define TRGMUX_IP_GTM_061                                   ((uint8)61U)
#define TRGMUX_IP_GTM_062                                   ((uint8)62U)
#define TRGMUX_IP_GTM_063                                   ((uint8)63U)
#define TRGMUX_IP_GTM_064                                   ((uint8)64U)
#define TRGMUX_IP_GTM_065                                   ((uint8)65U)
#define TRGMUX_IP_GTM_066                                   ((uint8)66U)
#define TRGMUX_IP_GTM_067                                   ((uint8)67U)
#define TRGMUX_IP_GTM_068                                   ((uint8)68U)
#define TRGMUX_IP_GTM_069                                   ((uint8)69U)
#define TRGMUX_IP_GTM_070                                   ((uint8)70U)
#define TRGMUX_IP_GTM_071                                   ((uint8)71U)
#define TRGMUX_IP_GTM_072                                   ((uint8)72U)
#define TRGMUX_IP_GTM_073                                   ((uint8)73U)
#define TRGMUX_IP_GTM_074                                   ((uint8)74U)
#define TRGMUX_IP_GTM_075                                   ((uint8)75U)
#define TRGMUX_IP_GTM_076                                   ((uint8)76U)
#define TRGMUX_IP_GTM_077                                   ((uint8)77U)
#define TRGMUX_IP_GTM_078                                   ((uint8)78U)
#define TRGMUX_IP_GTM_079                                   ((uint8)79U)
#define TRGMUX_IP_GTM_080                                   ((uint8)80U)
#define TRGMUX_IP_GTM_081                                   ((uint8)81U)
#define TRGMUX_IP_GTM_082                                   ((uint8)82U)
#define TRGMUX_IP_GTM_083                                   ((uint8)83U)
#define TRGMUX_IP_GTM_084                                   ((uint8)84U)
#define TRGMUX_IP_GTM_085                                   ((uint8)85U)
#define TRGMUX_IP_GTM_086                                   ((uint8)86U)
#define TRGMUX_IP_GTM_087                                   ((uint8)87U)
#define TRGMUX_IP_GTM_088                                   ((uint8)88U)
#define TRGMUX_IP_GTM_089                                   ((uint8)89U)
#define TRGMUX_IP_GTM_090                                   ((uint8)90U)
#define TRGMUX_IP_GTM_091                                   ((uint8)91U)
#define TRGMUX_IP_GTM_092                                   ((uint8)92U)
#define TRGMUX_IP_GTM_093                                   ((uint8)93U)
#define TRGMUX_IP_GTM_094                                   ((uint8)94U)
#define TRGMUX_IP_GTM_095                                   ((uint8)95U)
#define TRGMUX_IP_GTM_096                                   ((uint8)96U)
#define TRGMUX_IP_GTM_097                                   ((uint8)97U)
#define TRGMUX_IP_GTM_098                                   ((uint8)98U)
#define TRGMUX_IP_GTM_099                                   ((uint8)99U)
#define TRGMUX_IP_GTM_100                                   ((uint8)100U)
#define TRGMUX_IP_GTM_101                                   ((uint8)101U)
#define TRGMUX_IP_GTM_102                                   ((uint8)102U)
#define TRGMUX_IP_GTM_103                                   ((uint8)103U)
#define TRGMUX_IP_GTM_104                                   ((uint8)104U)
#define TRGMUX_IP_GTM_105                                   ((uint8)105U)
#define TRGMUX_IP_GTM_106                                   ((uint8)106U)
#define TRGMUX_IP_GTM_107                                   ((uint8)107U)
#define TRGMUX_IP_GTM_108                                   ((uint8)108U)
#define TRGMUX_IP_GTM_109                                   ((uint8)109U)
#define TRGMUX_IP_GTM_110                                   ((uint8)110U)
#define TRGMUX_IP_GTM_111                                   ((uint8)111U)
#define TRGMUX_IP_GTM_112                                   ((uint8)112U)
#define TRGMUX_IP_GTM_113                                   ((uint8)113U)
#define TRGMUX_IP_GTM_114                                   ((uint8)114U)
#define TRGMUX_IP_GTM_115                                   ((uint8)115U)
#define TRGMUX_IP_GTM_116                                   ((uint8)116U)
#define TRGMUX_IP_GTM_117                                   ((uint8)117U)
#define TRGMUX_IP_GTM_118                                   ((uint8)118U)
#define TRGMUX_IP_GTM_119                                   ((uint8)119U)
#define TRGMUX_IP_GTM_120                                   ((uint8)120U)
#define TRGMUX_IP_GTM_121                                   ((uint8)121U)
#define TRGMUX_IP_GTM_122                                   ((uint8)122U)
#define TRGMUX_IP_GTM_123                                   ((uint8)123U)
#define TRGMUX_IP_GTM_124                                   ((uint8)124U)
#define TRGMUX_IP_GTM_125                                   ((uint8)125U)
#define TRGMUX_IP_GTM_126                                   ((uint8)126U)
#define TRGMUX_IP_GTM_127                                   ((uint8)127U)
#define TRGMUX_IP_GTM_128                                   ((uint8)128U)
#define TRGMUX_IP_GTM_129                                   ((uint8)129U)
#define TRGMUX_IP_GTM_130                                   ((uint8)130U)
#define TRGMUX_IP_GTM_131                                   ((uint8)131U)
#define TRGMUX_IP_GTM_132                                   ((uint8)132U)
#define TRGMUX_IP_GTM_133                                   ((uint8)133U)
#define TRGMUX_IP_GTM_134                                   ((uint8)134U)
#define TRGMUX_IP_GTM_135                                   ((uint8)135U)
#define TRGMUX_IP_GTM_136                                   ((uint8)136U)
#define TRGMUX_IP_GTM_137                                   ((uint8)137U)
#define TRGMUX_IP_GTM_138                                   ((uint8)138U)
#define TRGMUX_IP_GTM_139                                   ((uint8)139U)
#define TRGMUX_IP_GTM_140                                   ((uint8)140U)
#define TRGMUX_IP_GTM_141                                   ((uint8)141U)
#define TRGMUX_IP_GTM_142                                   ((uint8)142U)
#define TRGMUX_IP_GTM_143                                   ((uint8)143U)
#define TRGMUX_IP_GTM_144                                   ((uint8)144U)
#define TRGMUX_IP_GTM_145                                   ((uint8)145U)
#define TRGMUX_IP_GTM_146                                   ((uint8)146U)
#define TRGMUX_IP_GTM_147                                   ((uint8)147U)
#define TRGMUX_IP_GTM_148                                   ((uint8)148U)
#define TRGMUX_IP_GTM_149                                   ((uint8)149U)
#define TRGMUX_IP_GTM_150                                   ((uint8)150U)
#define TRGMUX_IP_GTM_151                                   ((uint8)151U)
#define TRGMUX_IP_GTM_152                                   ((uint8)152U)
#define TRGMUX_IP_GTM_153                                   ((uint8)153U)
#define TRGMUX_IP_GTM_154                                   ((uint8)154U)
#define TRGMUX_IP_GTM_155                                   ((uint8)155U)
#define TRGMUX_IP_GTM_156                                   ((uint8)156U)
#define TRGMUX_IP_GTM_157                                   ((uint8)157U)
#define TRGMUX_IP_GTM_158                                   ((uint8)158U)
#define TRGMUX_IP_GTM_159                                   ((uint8)159U)
#define TRGMUX_IP_GTM_160                                   ((uint8)160U)
#define TRGMUX_IP_GTM_161                                   ((uint8)161U)
#define TRGMUX_IP_GTM_162                                   ((uint8)162U)
#define TRGMUX_IP_GTM_163                                   ((uint8)163U)
#define TRGMUX_IP_GTM_164                                   ((uint8)164U)
#define TRGMUX_IP_GTM_165                                   ((uint8)165U)
#define TRGMUX_IP_GTM_166                                   ((uint8)166U)
#define TRGMUX_IP_GTM_167                                   ((uint8)167U)
#define TRGMUX_IP_GTM_168                                   ((uint8)168U)
#define TRGMUX_IP_MSC_CH0                                   ((uint8)172U)
#define TRGMUX_IP_MSC_CH1                                   ((uint8)173U)     
#define TRGMUX_IP_MSC_CH2                                   ((uint8)174U)
#define TRGMUX_IP_MSC_CH3                                   ((uint8)175U)
#define TRGMUX_IP_MSC_CH4                                   ((uint8)176U)
#define TRGMUX_IP_MSC_CH5                                   ((uint8)177U)
#define TRGMUX_IP_MSC_CH6                                   ((uint8)178U)
#define TRGMUX_IP_MSC_CH7                                   ((uint8)179U)
#define TRGMUX_IP_MSC_CH8                                   ((uint8)180U)
#define TRGMUX_IP_MSC_CH9                                   ((uint8)181U)
#define TRGMUX_IP_MSC_CH10                                  ((uint8)182U)
#define TRGMUX_IP_MSC_CH11                                  ((uint8)183U)
#define TRGMUX_IP_MSC_CH12                                  ((uint8)184U)
#define TRGMUX_IP_MSC_CH13                                  ((uint8)185U)
#define TRGMUX_IP_MSC_CH14                                  ((uint8)186U)
#define TRGMUX_IP_MSC_CH15                                  ((uint8)187U)
#define TRGMUX_IP_MSC_CH16                                  ((uint8)188U)
#define TRGMUX_IP_MSC_CH17                                  ((uint8)189U)
#define TRGMUX_IP_MSC_CH18                                  ((uint8)190U)
#define TRGMUX_IP_MSC_CH19                                  ((uint8)191U)
#define TRGMUX_IP_MSC_CH20                                  ((uint8)192U)
#define TRGMUX_IP_MSC_CH21                                  ((uint8)193U)
#define TRGMUX_IP_MSC_CH22                                  ((uint8)194U)
#define TRGMUX_IP_MSC_CH23                                  ((uint8)195U)
#define TRGMUX_IP_MSC_CH24                                  ((uint8)196U)
#define TRGMUX_IP_MSC_CH25                                  ((uint8)197U)
#define TRGMUX_IP_MSC_CH26                                  ((uint8)198U)
#define TRGMUX_IP_MSC_CH27                                  ((uint8)199U)
#define TRGMUX_IP_MSC_CH28                                  ((uint8)200U)
#define TRGMUX_IP_MSC_CH29                                  ((uint8)201U)
#define TRGMUX_IP_MSC_CH30                                  ((uint8)202U)
#define TRGMUX_IP_MSC_CH31                                  ((uint8)203U)
#define TRGMUX_IP_MSC_CH32                                  ((uint8)204U)
#define TRGMUX_IP_MSC_CH33                                  ((uint8)205U)
#define TRGMUX_IP_MSC_CH34                                  ((uint8)206U)
#define TRGMUX_IP_MSC_CH35                                  ((uint8)207U)
#define TRGMUX_IP_MSC_CH36                                  ((uint8)208U)
#define TRGMUX_IP_MSC_CH37                                  ((uint8)209U)
#define TRGMUX_IP_MSC_CH38                                  ((uint8)210U)
#define TRGMUX_IP_MSC_CH39                                  ((uint8)211U)
#define TRGMUX_IP_MSC_CH40                                  ((uint8)212U)
#define TRGMUX_IP_MSC_CH41                                  ((uint8)213U)
#define TRGMUX_IP_MSC_CH42                                  ((uint8)214U)
#define TRGMUX_IP_MSC_CH43                                  ((uint8)215U)
#define TRGMUX_IP_MSC_CH44                                  ((uint8)216U)
#define TRGMUX_IP_MSC_CH45                                  ((uint8)217U)
#define TRGMUX_IP_MSC_CH46                                  ((uint8)218U)
#define TRGMUX_IP_MSC_CH47                                  ((uint8)219U)
#define TRGMUX_IP_MSC_CH48                                  ((uint8)220U)
#define TRGMUX_IP_MSC_CH49                                  ((uint8)221U)
#define TRGMUX_IP_MSC_CH50                                  ((uint8)222U)
#define TRGMUX_IP_MSC_CH51                                  ((uint8)223U)
#define TRGMUX_IP_MSC_CH52                                  ((uint8)224U)
#define TRGMUX_IP_MSC_CH53                                  ((uint8)225U)
#define TRGMUX_IP_MSC_CH54                                  ((uint8)226U)
#define TRGMUX_IP_MSC_CH55                                  ((uint8)227U)
#define TRGMUX_IP_MSC_CH56                                  ((uint8)228U)
#define TRGMUX_IP_MSC_CH57                                  ((uint8)229U)
#define TRGMUX_IP_MSC_CH58                                  ((uint8)230U)
#define TRGMUX_IP_MSC_CH59                                  ((uint8)231U)
#define TRGMUX_IP_MSC_CH60                                  ((uint8)232U)
#define TRGMUX_IP_MSC_CH61                                  ((uint8)233U)
#define TRGMUX_IP_MSC_CH62                                  ((uint8)234U)
#define TRGMUX_IP_MSC_CH63                                  ((uint8)235U)
#define TRGMUX_IP_CTU_TRG0                                  ((uint8)236U)
#define TRGMUX_IP_CTU_TRG1                                  ((uint8)237U)
#define TRGMUX_IP_CTU_TRG2                                  ((uint8)238U)
#define TRGMUX_IP_CTU_TRG3                                  ((uint8)239U)
#define TRGMUX_IP_SINC_TRG0                                 ((uint8)240U)
#define TRGMUX_IP_SINC_TRG1                                 ((uint8)241U)
#define TRGMUX_IP_SINC_TRG2                                 ((uint8)242U)
#define TRGMUX_IP_SINC_TRG3                                 ((uint8)243U)

#ifdef __cplusplus
}
#endif

#endif  /* TRGMUX_IP_CFG_DEFINES_H_ */
